services:
  postgres:
    image: postgres:15
    container_name: gitea_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    volumes:
      - /opt/gitea/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - gitea_net
  
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    volumes:
      - /opt/gitea/data:/data
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - gitea_net
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=${POSTGRES_DB}
      - GITEA__database__USER=${POSTGRES_USER}
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD}
      - GITEA__server__ROOT_URL=https://gitea.devsecorpion.sbs
      - GITEA__server__DOMAIN=gitea.devsecorpion.sbs
    ports:
      - "127.0.0.1:3000:3000"
  
  runner:
    image: gitea/act_runner:latest
    container_name: gitea_runner
    depends_on:
      - gitea
    networks:
      - gitea_net
    environment:
      - GITEA_INSTANCE_URL=https://gitea.devsecorpion.sbs
      - GITEA_RUNNER_REGISTRATION_TOKEN=${GITEA_RUNNER_TOKEN}
      - GITEA_RUNNER_NAME=global-runner
      - GITEA_RUNNER_LABELS=ubuntu-latest:docker://gitea/runner-images:ubuntu-latest
    volumes:
     - ./runner-data:/data
     - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  runner_2:
    image: gitea/act_runner:latest
    container_name: gitea_runner2
    depends_on:
      - gitea
    networks:
      - gitea_net
    environment:
      - GITEA_INSTANCE_URL=https://gitea.devsecorpion.sbs
      - GITEA_RUNNER_REGISTRATION_TOKEN=${GITEA_RUNNER_TOKEN}
      - GITEA_RUNNER_NAME=global-runner2
      - GITEA_RUNNER_LABELS=ubuntu-latest:docker://gitea/runner-images:ubuntu-latest
    volumes:
     - ./runner-data-2:/data
     - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  runner_3:
    image: gitea/act_runner:latest
    container_name: gitea_runner3
    depends_on:
      - gitea
    networks:
      - gitea_net
    environment:
      - GITEA_INSTANCE_URL=https://gitea.devsecorpion.sbs
      - GITEA_RUNNER_REGISTRATION_TOKEN=${GITEA_RUNNER_TOKEN}
      - GITEA_RUNNER_NAME=global-runner3
      - GITEA_RUNNER_LABELS=ubuntu-latest:docker://gitea/runner-images:ubuntu-latest
    volumes:
     - ./runner-data-3:/data
     - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped


networks:
  gitea_net:
    driver: bridge
